# Gitpod + Cursor + Cline 完全自動化設定 (v2)

tasks:
  - name: Setup
    init: |
      # 永続化と拡張機能インストールのためのセットアップスクリプトを実行
      chmod +x .gitpod/setup.sh
      .gitpod/setup.sh
      gp sync-done setup
    command: |
      # .bashrcを読み込み、エイリアスを有効化
      source ~/.bashrc
      clear
      
      echo "================================================================"
      echo "✅ Gitpod環境の準備が完了しました。"
      echo ""
      echo "   次のコマンドでCursorへのSSH接続情報を確認できます："
      echo ""
      echo "      cursor-ssh"
      echo ""
      echo "================================================================"

# 公開するポート
ports:
  - port: 3000-8999
    onOpen: ignore

# ワークスペースのタイムアウト設定
workspaceTimeout: 12h

# Prebuild設定
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addBadge: true
