# .gitpod.yml
tasks:
  - init: |
      # 初回ビルド時に実行
      npm install -g @anthropic-ai/claude-code
      pip install duckduckgo-search
    command: |
      # 毎回のワークスペース起動時に実行
      echo "✅ Workspace ready!"
      
      # Claude Codeの再インストール（必要に応じて）
      if ! command -v claude &> /dev/null; then
        npm install -g @anthropic-ai/claude-code
      fi
      
      gp sync-done setup

vscode:
  extensions:
    - saoudrizwan.claude-dev

workspaceTimeout: 6h

# Prebuildsを有効化
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true