# .gitpod.yml を更新
tasks:
  - name: Setup Development Environment
    command: |
      # Claude Codeのインストール
      if ! command -v claude &> /dev/null; then
        echo "Installing Claude Code..."
        npm install -g @anthropic-ai/claude-code
      fi
      
      # Python依存関係のインストール
      if [ -f "requirements.txt" ]; then
        pip install -r requirements.txt
      fi
      
      # AGNOプロジェクト特有の依存関係
      pip install duckduckgo-search
      
      echo "✅ All setup complete!"
      echo "🚀 Type 'claude' to start Claude Code"

vscode:
  extensions:
    - saoudrizwan.claude-dev

workspaceTimeout: 6h